### ISSUE TITLE
AsepriteNativeParser parsing Forward AnimationTypes to AnimationStrategy.End

### ISSUE THREAD

**Issue by dericatienza** [excaliburjs/excalibur-aseprite#200]
The current behaviour of `AsepriteNativeParser` is to set animations' `strategy` to `AnimationStrategy.End` when its type is `AnimationTypes.Forward`. This is inconsistent with. `AsepriteJsonParser` which sets the `strategy` to `AnimationStrategy.Loop` by default or when the tag direction is 'forward'.

I suggest updating `AsepriteNativeParser` to follow the same behaviour and set animations `strategy` to `AnimationStrategy.Loop` by default.

`AsepriteNativeParser`'s strategy setting logic:
https://github.com/excaliburjs/excalibur-aseprite/blob/e27ae18ac7c114060f771de54c338dbd9043da4b/src/AsepriteNativeParser.ts#L96-L101

`AsepriteJsonParser`'s strategy setting logic:
https://github.com/excaliburjs/excalibur-aseprite/blob/e27ae18ac7c114060f771de54c338dbd9043da4b/src/AsepriteJsonParser.ts#L54-L64

**Comment by eonarheim** [comment]
@dericatienza Good find! Definitely agree and want these to be consistent!

**Comment by dericatienza** [comment]
Great! I submitted a PR https://github.com/excaliburjs/excalibur-aseprite/pull/201.
